SELECT 
  TO_CHAR(BEGIN_TIME, 'YYYY-MM-DD HH24:MI') AS begin_time,
  UNDOTSN, 
  UNDOBLKS, 
  TXNCOUNT, 
  MAXQUERYLEN, 
  SSOLDERRCNT, 
  NOSPACEERRCNT, 
  UNXPSTEALCNT
FROM 
  v$undostat 
ORDER BY 
  begin_time DESC;